prevent explosion in Django's debug helper due to non-standard encoding
…django/views/debug.py", line 406, in _get_lines_from_file
    source = [six.text_type(sline, encoding, 'replace') for sline in source]
LookupError: unknown encoding: utf-8-unix